# Generated by Cloud66 Starter
FROM ubuntu:focal
#install all the dependencies
RUN apt-get update 
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y curl apache2 \
          libapache2-mod-php \
          php-pear \
          php \
          php-curl \
          php-dev \
          php-gd \
          php-intl \
          php-json \
          php-ldap \
          php-mbstring \
          php-pgsql \
          php-soap \
          php-xml \
          libyaz4-dev 

#RUN wget https://github.com/vufind-org/vufind/releases/download/v6.1.1/vufind_6.1.1.deb
RUN service apache2 start
#COPY debs/vufind_6.1.1.deb /tmp
#RUN dpkg -i /tmp/vufind_6.1.1.deb || true
#RUN apt-get install -f -y

#change ownership
#RUN chown -R www-data:www-data $APP_HOME
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y  apt-utils sudo || true
ENV TZ=America/Argentina/Mendoza
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#EXPOSE 8080
#ADD sample.mrc /tmp/sample.mrc
#RUN . /etc/profile.d/vufind.sh \
#    && sudo -u solr /usr/local/vufind/solr.sh start \
#    && /usr/local/vufind/import-marc.sh /tmp/sample.mrc
RUN yes "" |pecl install yaz

# configure apache
EXPOSE 80
EXPOSE 443
COPY apache2-foreground /usr/bin/
RUN chmod +x /usr/bin/apache2-foreground 
CMD ["apache2-foreground"]
